[package]
name = "mlkem-ref"
description = "A reference Rust implementation of the ML-KEM post-quantum key encapsulation mechanism."
repository = "https://github.com/kriskwiatkowski/mlkem-ref"
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"
author = "Kris Kwiatkowski <kris@amongbytes.com>"
keywords = ["cryptography", "post-quantum", "kem", "code-based", "hqc"]
categories = ["cryptography", "no-std"]

[dependencies]
sha3 = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"

[dev-dependencies]
criterion = "=0.8.2"
criterion-cycles-per-byte = "0.8.0"

[[bench]]
name = "bench"
harness = false
